server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/jongminchung/Desktop/jongmin/project/spring-cloud-config

